### ISSUE TITLE
Make sure you are including the vendor/autoload.php

### ISSUE THREAD

**Issue by rvpatel** [moxie-lean/wp-acf-select-gravityform#10]
Make sure you are including the vendor/autoload.php file for the ACF Gravity Form Select component.

**Comment by rvpatel** [comment]
Please provide a full information how to setup plugin or provide full code.
Lean\Acf\Types\Gravity  - whats the use of this name space?

whats name required or which name based field create?

**Comment by Fcog** [comment]
try running `composer install` in the plugin's directory
