### ISSUE TITLE
Make sure you are including the vendor/autoload.php

### ISSUE THREAD

**Issue by yumyo** [moxie-lean/wp-acf-select-gravityform#8]
Hi,

we're already using composer to manage our plugins, however trying to activate `wp-acf-select-gravityform` we get `Make sure you are including the vendor/autoload.php file for the ACF Gravity Form Select component.
`

**Comment by mitogh** [comment]
Hey @yumyo 

There are two ways you can archive this if you are using composer already to manage your plugins 

1.- you need to make sure you are including `autoload.php`  in `wp-config.php`. 

Like: 

``` php
include_once 'autoload.php';
```

2.- Or you can add a `post-install` script in your `composer.json` file to generate the files for you: 

By adding the `scripts` section on the `composer.json`. 

``` json
  "scripts": {
    "install-gravity-forms-select": "cd ./wp-content/plugins/acf-gravity-forms-select && composer install && composer update",
    "post-install-cmd": ["@install-gravity-forms-select"]
  },
```

So every time you run `composer install` the`install-gravity-form-select` is going to be executed or you can manually run as well: 

```
composer install-gravity-forms-select
```

Let me know if you have more questions. I'm closing this one for now but happy to answers any other questions that you might have.
